using System;
using System.Collections.Generic;

namespace Phoron.Core
{
    /// <summary>
    /// Terjemahan antarmuka.
    ///
    /// Kuncinya adalah teks Indonesia itu sendiri, bukan kode seperti
    /// "nav.beranda". Dua alasan: bahasa asal aplikasi ini memang Indonesia,
    /// jadi tidak perlu kamus sama sekali untuk bahasa itu; dan teks yang belum
    /// diterjemahkan jatuh kembali ke Indonesia yang benar, bukan ke kode mentah
    /// yang tidak berarti apa-apa bagi pengguna.
    ///
    /// Bahasa Banjar dan Jawa sengaja tidak memaksakan padanan untuk istilah
    /// teknis yang memang dipakai apa adanya sehari-hari (port, profil, log).
    /// Menerjemahkannya justru membuat layar lebih sulit dibaca, bukan lebih
    /// ramah.
    ///
    /// Kosakata Banjar di sini BUKAN karangan sendiri. Dasarnya dua sumber yang
    /// ditulis penutur Banjar:
    ///   1. bjn.json milik MediaWiki (translatewiki.net) - 2.104 pesan
    ///      antarmuka perangkat lunak yang sudah punya padanan Indonesianya,
    ///      jadi persis jenis teks yang dibutuhkan di sini;
    ///   2. Wikipidia Banjar, untuk menghitung apakah sebuah kata bentukan
    ///      benar-benar dipakai.
    /// Dari situ misalnya "halum" (karangan) diganti "balum", "Batalakan"
    /// jadi "Pasahakan", "barataan" jadi "samunyaan", dan "Versi" TIDAK jadi
    /// "Virsi" - bentuk terakhir ini cuma muncul sekali, sedangkan "versi"
    /// ribuan kali.
    /// </summary>
    public static class Lang
    {
        public const string Indonesia = "id";
        public const string Inggris = "en";
        public const string Jawa = "jv";
        public const string Banjar = "bjn";

        /// <summary>Kode bahasa yang sedang dipakai.</summary>
        public static string Kode = Indonesia;

        /// <summary>Diangkat setiap kali bahasa berganti, supaya layar bisa menggambar ulang.</summary>
        public static event Action Berubah;

        public static void Pakai(string kode)
        {
            var baru = Sah(kode) ? kode : Indonesia;
            if (baru == Kode) return;
            Kode = baru;
            var h = Berubah;
            if (h != null) h();
        }

        public static bool Sah(string kode)
        {
            return kode == Indonesia || kode == Inggris || kode == Jawa || kode == Banjar;
        }

        public static string NamaBahasa(string kode)
        {
            switch (kode)
            {
                case Inggris: return "English";
                case Jawa: return "Basa Jawa";
                case Banjar: return "Bahasa Banjar";
                default: return "Bahasa Indonesia";
            }
        }

        public static string[] Semua { get { return new[] { Indonesia, Inggris, Jawa, Banjar }; } }

        /// <summary>Terjemahkan satu teks. Yang tidak ada padanannya tetap tampil dalam bahasa Indonesia.</summary>
        public static string T(string teks)
        {
            if (string.IsNullOrEmpty(teks) || Kode == Indonesia) return teks;
            Dictionary<string, string> kamus;
            if (!Kamus.TryGetValue(Kode, out kamus)) return teks;
            string hasil;
            return kamus.TryGetValue(teks, out hasil) ? hasil : teks;
        }

        /// <summary>Terjemahkan lalu sisipkan nilai, mis. T("Port {0} bebas.", 80).</summary>
        public static string T(string teks, params object[] isi)
        {
            return string.Format(T(teks), isi);
        }

        static readonly Dictionary<string, Dictionary<string, string>> Kamus =
            new Dictionary<string, Dictionary<string, string>>
            {
                { Inggris, Inggris_() },
                { Jawa, Jawa_() },
                { Banjar, Banjar_() },
            };

        static Dictionary<string, string> Inggris_()
        {
            return new Dictionary<string, string>(StringComparer.Ordinal)
            {
                // Simpan-seketika di Profil dan Ekstensi
                { "Nyalakan ulang web server",
                  "Restart the web server" },
                { "Switch ke profil ini",
                  "Switch to this profile" },
                { "Setiap centangan langsung tersimpan ke profil dan php.ini ditulis ulang - tidak ada tombol simpan.",
                  "Every tick is saved to the profile straight away and php.ini is rewritten - there is no save button." },
                { "Setiap perubahan langsung tersimpan ke berkas profil - tidak ada tombol simpan.",
                  "Every change is saved to the profile file straight away - there is no save button." },
                // Halaman Tentang
                { "Tentang",
                  "About" },
                { "Yang sedang dipakai",
                  "Currently in use" },
                { "Tautan",
                  "Links" },
                { "Halaman proyek di GitHub",
                  "Project page on GitHub" },
                { "Salin info versi",
                  "Copy version info" },
                { "pengguna biasa",
                  "ordinary user" },
                { "Info versi sudah disalin ke papan klip.",
                  "Version info copied to the clipboard." },
                { "Lingkungan pengembangan web lokal: Apache, PHP, MySQL, dan Node dalam satu tempat, dengan kombinasi versi yang bisa disimpan sebagai profil lalu ditukar sekali klik.",
                  "A local web development environment: Apache, PHP, MySQL and Node in one place, with version combinations you can save as profiles and swap in one click." },
                { "Phoron memakai Apache, PHP, MySQL/MariaDB, Nginx, dan Node.js yang masing-masing punya lisensi sendiri. Phoron tidak pernah menulis ke dalam folder bin milik program itu - seluruh konfigurasi yang dihasilkan disimpan di folder etc.",
                  "Phoron uses Apache, PHP, MySQL/MariaDB, Nginx and Node.js, each under its own licence. Phoron never writes into those programs' bin folders - every configuration it generates is kept in the etc folder." },
                // Daftar hosts sekali jalan
                { "Daftarkan nama situs sekali",
                  "Register site names once" },
                { "Saat dinyalakan Windows lewat autostart, Phoron selalu jalan tanpa hak Administrator - Windows memang begitu, supaya tidak ada kotak UAC di tiap boot. Entri berkas hosts sendiri menetap, jadi cukup didaftarkan sekali: sesudah itu nama .test tetap hidup walau Phoron jalan sebagai pengguna biasa.",
                  "When Windows starts it through autostart, Phoron always runs without Administrator rights - that is Windows' own rule, so there is no UAC box on every boot. Hosts file entries persist, so registering them once is enough: after that .test names keep working even while Phoron runs as an ordinary user." },
                // Teks layar yang tersisa
                { "Menyambung...",
                  "Connecting..." },
                { "Batalkan",
                  "Cancel" },
                { "Apache berhenti",
                  "Apache stopped" },
                { "MySQL berhenti",
                  "MySQL stopped" },
                { "Centang ekstensi yang dipakai profil aktif.",
                  "Tick the extensions the active profile uses." },
                { "Cari ekstensi...",
                  "Search extensions..." },
                { "Satu folder per baris; boleh lebih dari satu. Yang paling atas jadi akar utama (dilayani http://localhost). Kosongkan untuk memakai www bawaan.",
                  "One folder per line; more than one is fine. The topmost one becomes the main root (served at http://localhost). Leave it empty to use the built-in www." },
                { "Phoron mulai langsung mengecil ke baki sistem, tanpa memunculkan jendela.",
                  "Phoron starts straight into the system tray, without showing a window." },
                { "Hanya alamat akar yang dialihkan. Subfolder seperti /simpdam/ tidak tersentuh, dan index.php milik folder proyek tetap bisa dibuka di /index.php. Matikan kalau akar folder proyek Anda memang aplikasi sendiri.",
                  "Only the root address is redirected. Subfolders such as /simpdam/ are untouched, and the project folder's own index.php is still reachable at /index.php. Turn this off if your project root really is an application of its own." },
                { "Baku mati agar Phoron ringan: log akses Apache dan seluruh keluaran layanan tidak ditulis (mysqld sendiri mencetak ratusan baris tiap kali menyala). Log GALAT Apache, MySQL, dan PHP tetap menyala — itulah yang menjelaskan kalau ada yang rusak.",
                  "Off by default to keep Phoron light: Apache access logs and all service output are not written (mysqld alone prints hundreds of lines on every start). Apache, MySQL and PHP ERROR logs stay on — those are what explain a breakage." },
                { @"Baku: php.ini ditulis ke etc\php\<versi>\ dan folder PHP tidak disentuh. Nyalakan kalau Anda ingin php.exe dari editor atau Composer di luar Phoron ikut memakai setelan yang sama. Hati-hati bila versi PHP-nya dipinjam dari Laragon - berkasnya dipakai bersama. php.ini asli dicadangkan sekali ke php.ini.sebelum-phoron.",
                  @"Default: php.ini is written to etc\php\<version>\ and the PHP folder is left alone. Turn this on if you want php.exe from your editor or from Composer outside Phoron to use the same settings. Be careful when the PHP version is borrowed from Laragon - the file is shared. The original php.ini is backed up once to php.ini.sebelum-phoron." },
                { "Satu folder per baris. Folder bin Laragon boleh ikut - Phoron tidak pernah menulis ke dalamnya.",
                  "One folder per line. Laragon's bin folder may be included - Phoron never writes into it." },
                { "Pengecekan dilewati kalau baru dilakukan dalam 6 jam terakhir - API GitHub tanpa token dibatasi 60 permintaan per jam.",
                  "The check is skipped if one already ran within the last 6 hours - GitHub's API without a token is capped at 60 requests per hour." },
                { "Tiap subfolder di www otomatis dapat alamat sendiri.",
                  "Every subfolder in www automatically gets its own address." },
                { "Semua folder versi yang ditemukan di folder bin yang terdaftar. Folder bin Laragon ikut dipindai bila ada.",
                  "Every version folder found in the registered bin folders. Laragon's bin folder is scanned too when it is there." },
                { @"Katalog unduhan (etc\catalog.ini)",
                  @"Download catalogue (etc\catalog.ini)" },
                { "Katalog lokal",
                  "Local catalogue" },
                { "Paket diunduh ke folder bin milik Phoron, tidak menyentuh folder Laragon.",
                  "Packages are downloaded into Phoron's own bin folder, never touching Laragon's." },
                // Navigasi dan status
                { "Beranda", "Home" },
                { "Profil", "Profiles" },
                { "Versi", "Versions" },
                { "Situs", "Sites" },
                { "Node / TS", "Node / TS" },
                { "Ekstensi PHP", "PHP extensions" },
                { "Log", "Logs" },
                { "Pengaturan", "Settings" },
                { "Nyalakan semua", "Start all" },
                { "Matikan semua", "Stop all" },
                { "Keluar", "Quit" },
                { "(belum ada profil)", "(no profile yet)" },
                { "berhenti", "stopped" },
                { "jalan", "running" },
                { "menyalakan", "starting" },
                { "mematikan", "stopping" },
                { "gagal", "failed" },

                // Beranda
                { "Pilih profil, lalu nyalakan. Ganti profil berarti ganti versi PHP, Apache, dan MySQL sekaligus.",
                  "Pick a profile, then start. Switching profiles changes PHP, Apache and MySQL together." },
                { "Profil aktif", "Active profile" },
                { "Switch & Jalankan", "Switch & Run" },
                { "Switch", "Switch" },
                { "Perhatian", "Heads up" },
                { "Pintasan", "Shortcuts" },
                { "Aktivitas", "Activity" },
                { "Buka www", "Open www" },
                { "Buka localhost", "Open localhost" },
                { "Beranda Phoron", "Phoron home" },
                { "Terminal", "Terminal" },
                { "Uji konfigurasi Apache", "Test Apache config" },
                { "Buat sertifikat SSL", "Create SSL certificate" },
                { "Percayai sertifikat SSL", "Trust SSL certificate" },
                { "Buat ulang sertifikat SSL", "Recreate SSL certificate" },
                { "Folder etc", "etc folder" },
                { "Unduh pembaruan", "Download update" },
                { "Jalankan ulang sebagai Administrator", "Restart as Administrator" },
                { "Hentikan proses yang tertinggal", "Stop leftover processes" },
                { "belum dipilih di profil", "not set in this profile" },

                // Profil
                { "Satu profil = satu kombinasi versi + port. Simpan sebanyak yang perlu, lalu tinggal switch.",
                  "One profile = one set of versions and ports. Save as many as you need, then just switch." },
                { "Profil baru", "New profile" },
                { "Duplikat", "Duplicate" },
                { "Hapus", "Delete" },
                { "Nama profil", "Profile name" },
                { "Web server", "Web server" },
                { "Versi PHP", "PHP version" },
                { "Versi Apache", "Apache version" },
                { "Versi Nginx", "Nginx version" },
                { "Versi MySQL / MariaDB", "MySQL / MariaDB version" },
                { "Port HTTP", "HTTP port" },
                { "Port HTTPS", "HTTPS port" },
                { "Port MySQL", "MySQL port" },
                { "Folder proyek", "Project folders" },
                { "Tambah folder...", "Add folder..." },
                { "Akhiran nama situs", "Site name suffix" },
                { "Catatan", "Notes" },
                { "Simpan", "Save" },
                { "Simpan lalu switch ke profil ini", "Save and switch to this profile" },

                // Versi
                { "Versi terpasang", "Installed versions" },
                { "Jenis", "Kind" },
                { "Toolset", "Toolset" },
                { "Arsitektur", "Architecture" },
                { "Folder", "Folder" },
                { "Sumber", "Source" },
                { "Pindai ulang", "Rescan" },
                { "Tambah folder bin", "Add bin folder" },
                { "Buka folder versi", "Open version folder" },
                { "Pasang versi baru", "Install a new version" },
                { "Unduh & pasang", "Download & install" },

                // Situs
                { "Buat situs", "Create site" },
                { "Alamat", "Address" },
                { "Document root", "Document root" },
                { "hosts", "hosts" },
                { "vhost", "vhost" },
                { "Buka di browser", "Open in browser" },
                { "Buka folder", "Open folder" },
                { "Terminal di sini", "Terminal here" },
                { "Segarkan & sinkronkan", "Refresh & sync" },
                { "Buka berkas hosts", "Open hosts file" },

                // Node
                { "Node / TypeScript", "Node / TypeScript" },
                { "Jalankan Next.js, Astro, Vite, dan proyek Node lain dari folder mana pun.",
                  "Run Next.js, Astro, Vite and other Node projects from any folder." },
                { "Proyek", "Project" },
                { "Kerangka", "Framework" },
                { "Perintah", "Command" },
                { "Status", "Status" },
                { "Skrip", "Script" },
                { "Node", "Node" },
                { "Jalankan", "Run" },
                { "Hentikan", "Stop" },
                { "Tambah proyek...", "Add project..." },
                { "Buka alamat", "Open address" },
                { "Hapus dari daftar", "Remove from list" },
                { "Keluaran", "Output" },

                // Ekstensi
                { "Setelan php.ini yang sering diubah", "Commonly changed php.ini settings" },
                { "Simpan ke profil", "Save to profile" },
                { "Ambil dari php.ini asli", "Take from original php.ini" },
                { "Buka php.ini hasil", "Open generated php.ini" },
                { "Uji: php -m", "Test: php -m" },
                { "short_open_tag (perlu untuk banyak proyek lama)",
                  "short_open_tag (needed by many legacy projects)" },

                // Log
                { "Semua log Apache, MySQL, PHP, dan Phoron ada di folder logs.",
                  "All Apache, MySQL, PHP and Phoron logs live in the logs folder." },
                { "Muat ulang", "Reload" },
                { "Kosongkan", "Clear" },
                { "Ikuti", "Follow" },

                // Pengaturan
                { "Setiap perubahan langsung tersimpan ke phoron.ini - tidak ada tombol simpan.",
                  "Every change is saved to phoron.ini immediately - there is no save button." },
                { "Tampilan", "Appearance" },
                { "Tema", "Theme" },
                { "Bahasa", "Language" },
                { "Ikut Windows", "Follow Windows" },
                { "Terang", "Light" },
                { "Gelap", "Dark" },
                { "Jalankan Phoron saat Windows dinyalakan", "Start Phoron when Windows starts" },
                { "Nyalakan layanan otomatis saat Phoron dibuka",
                  "Start services automatically when Phoron opens" },
                { "Tombol tutup mengecilkan ke baki sistem, bukan keluar",
                  "Close button minimises to the system tray instead of quitting" },
                { "Buat vhost otomatis untuk tiap folder di www",
                  "Create a vhost automatically for every folder in www" },
                { "Sinkronkan berkas hosts Windows (butuh Administrator)",
                  "Sync the Windows hosts file (needs Administrator)" },
                { "Tampilkan beranda Phoron di http://localhost/",
                  "Show the Phoron home page at http://localhost/" },
                { "Catat log rinci", "Write verbose logs" },
                { "Tulis php.ini ke dalam folder PHP", "Write php.ini into the PHP folder" },
                { "Folder bin yang dipindai", "Scanned bin folders" },
                { "Status hak akses", "Privilege status" },
                { "Folder Phoron", "Phoron folder" },
                { "Buka folder instalasi", "Open install folder" },
                { "Buka phoron.ini", "Open phoron.ini" },
                { "Buang blok hosts milik Phoron", "Remove Phoron's hosts block" },
                { "Pembaruan", "Updates" },
                { "Cek rilis baru di GitHub saat Phoron dibuka",
                  "Check GitHub for new releases when Phoron opens" },
                { "Cek pembaruan sekarang", "Check for updates now" },
                { "Buka halaman rilis", "Open releases page" },
            };
        }

        static Dictionary<string, string> Jawa_()
        {
            return new Dictionary<string, string>(StringComparer.Ordinal)
            {
                // Simpan-seketika di Profil dan Ekstensi
                { "Nyalakan ulang web server",
                  "Uripna maneh web server" },
                { "Switch ke profil ini",
                  "Ganti menyang profil iki" },
                { "Setiap centangan langsung tersimpan ke profil dan php.ini ditulis ulang - tidak ada tombol simpan.",
                  "Saben centhangan langsung disimpen menyang profil lan php.ini ditulis maneh - ora ana tombol simpen." },
                { "Setiap perubahan langsung tersimpan ke berkas profil - tidak ada tombol simpan.",
                  "Saben owahan langsung disimpen menyang berkas profil - ora ana tombol simpen." },
                // Halaman Tentang
                { "Tentang",
                  "Ngenani" },
                { "Yang sedang dipakai",
                  "Sing lagi dianggo" },
                { "Tautan",
                  "Pranala" },
                { "Halaman proyek di GitHub",
                  "Kaca proyek ing GitHub" },
                { "Salin info versi",
                  "Salin info versi" },
                { "pengguna biasa",
                  "pangguna biasa" },
                { "Info versi sudah disalin ke papan klip.",
                  "Info versi wis disalin menyang papan klip." },
                { "Lingkungan pengembangan web lokal: Apache, PHP, MySQL, dan Node dalam satu tempat, dengan kombinasi versi yang bisa disimpan sebagai profil lalu ditukar sekali klik.",
                  "Lingkungan pangembangan web lokal: Apache, PHP, MySQL, lan Node ing sak panggonan, kanthi kombinasi versi sing bisa disimpen minangka profil banjur diganti sepisan klik." },
                { "Phoron memakai Apache, PHP, MySQL/MariaDB, Nginx, dan Node.js yang masing-masing punya lisensi sendiri. Phoron tidak pernah menulis ke dalam folder bin milik program itu - seluruh konfigurasi yang dihasilkan disimpan di folder etc.",
                  "Phoron nganggo Apache, PHP, MySQL/MariaDB, Nginx, lan Node.js sing saben-sabene duwe lisensi dhewe. Phoron ora tau nulis ing njero folder bin duweke program kuwi - kabeh konfigurasi sing digawe disimpen ing folder etc." },
                // Daftar hosts sekali jalan
                { "Daftarkan nama situs sekali",
                  "Daftarake ngaran situs sepisan" },
                { "Saat dinyalakan Windows lewat autostart, Phoron selalu jalan tanpa hak Administrator - Windows memang begitu, supaya tidak ada kotak UAC di tiap boot. Entri berkas hosts sendiri menetap, jadi cukup didaftarkan sekali: sesudah itu nama .test tetap hidup walau Phoron jalan sebagai pengguna biasa.",
                  "Nalika diuripake Windows liwat autostart, Phoron tansah mlaku tanpa hak Administrator - pancen aturane Windows, supaya ora ana kothak UAC saben boot. Entri berkas hosts kuwi tetep, dadi cukup didaftarake sepisan: sawise kuwi jeneng .test tetep urip sanajan Phoron mlaku minangka pangguna biasa." },
                // Teks layar yang tersisa
                { "Menyambung...",
                  "Nyambung..." },
                { "Batalkan",
                  "Batalake" },
                { "Apache berhenti",
                  "Apache mandheg" },
                { "MySQL berhenti",
                  "MySQL mandheg" },
                { "Centang ekstensi yang dipakai profil aktif.",
                  "Centhangi ekstensi sing dianggo profil aktif." },
                { "Cari ekstensi...",
                  "Golek ekstensi..." },
                { "Satu folder per baris; boleh lebih dari satu. Yang paling atas jadi akar utama (dilayani http://localhost). Kosongkan untuk memakai www bawaan.",
                  "Siji folder saben baris; oleh luwih saka siji. Sing paling ndhuwur dadi oyod utama (dilayani http://localhost). Kosongake kanggo nganggo www bawaan." },
                { "Phoron mulai langsung mengecil ke baki sistem, tanpa memunculkan jendela.",
                  "Phoron mlaku langsung ngalih menyang baki sistem, tanpa mbukak jendhela." },
                { "Hanya alamat akar yang dialihkan. Subfolder seperti /simpdam/ tidak tersentuh, dan index.php milik folder proyek tetap bisa dibuka di /index.php. Matikan kalau akar folder proyek Anda memang aplikasi sendiri.",
                  "Mung alamat oyod sing dialihake. Subfolder kaya /simpdam/ ora diganggu, lan index.php duweke folder proyek isih bisa dibukak ing /index.php. Patenana yen oyod folder proyek sampeyan pancen aplikasi dhewe." },
                { "Baku mati agar Phoron ringan: log akses Apache dan seluruh keluaran layanan tidak ditulis (mysqld sendiri mencetak ratusan baris tiap kali menyala). Log GALAT Apache, MySQL, dan PHP tetap menyala — itulah yang menjelaskan kalau ada yang rusak.",
                  "Bawaane mati supaya Phoron entheng: log akses Apache lan kabeh metune layanan ora ditulis (mysqld dhewe nyithak atusan baris saben urip). Log GALAT Apache, MySQL, lan PHP tetep urip — kuwi sing nerangake yen ana sing rusak." },
                { @"Baku: php.ini ditulis ke etc\php\<versi>\ dan folder PHP tidak disentuh. Nyalakan kalau Anda ingin php.exe dari editor atau Composer di luar Phoron ikut memakai setelan yang sama. Hati-hati bila versi PHP-nya dipinjam dari Laragon - berkasnya dipakai bersama. php.ini asli dicadangkan sekali ke php.ini.sebelum-phoron.",
                  @"Bawaane: php.ini ditulis ing etc\php\<versi>\ lan folder PHP ora disenggol. Uripna yen sampeyan pengin php.exe saka editor utawa Composer ing njaba Phoron melu nganggo setelan sing padha. Ati-ati yen versi PHP-ne nyilih saka Laragon - berkase dianggo bareng. php.ini asli dicadhangake sepisan menyang php.ini.sebelum-phoron." },
                { "Satu folder per baris. Folder bin Laragon boleh ikut - Phoron tidak pernah menulis ke dalamnya.",
                  "Siji folder saben baris. Folder bin Laragon oleh melu - Phoron ora tau nulis ing njerone." },
                { "Pengecekan dilewati kalau baru dilakukan dalam 6 jam terakhir - API GitHub tanpa token dibatasi 60 permintaan per jam.",
                  "Pamriksan dilewati yen lagi wae dilakoni sajrone 6 jam pungkasan - API GitHub tanpa token diwatesi 60 panjaluk saben jam." },
                { "Tiap subfolder di www otomatis dapat alamat sendiri.",
                  "Saben subfolder ing www otomatis oleh alamat dhewe." },
                { "Semua folder versi yang ditemukan di folder bin yang terdaftar. Folder bin Laragon ikut dipindai bila ada.",
                  "Kabeh folder versi sing ketemu ing folder bin sing kadaftar. Folder bin Laragon melu dipindhai yen ana." },
                { @"Katalog unduhan (etc\catalog.ini)",
                  @"Katalog undhuhan (etc\catalog.ini)" },
                { "Katalog lokal",
                  "Katalog lokal" },
                { "Paket diunduh ke folder bin milik Phoron, tidak menyentuh folder Laragon.",
                  "Paket diundhuh menyang folder bin duweke Phoron, ora nyenggol folder Laragon." },
                { "Beranda", "Ngarep" },
                { "Profil", "Profil" },
                { "Versi", "Versi" },
                { "Situs", "Situs" },
                { "Ekstensi PHP", "Ekstensi PHP" },
                { "Pengaturan", "Setelan" },
                { "Nyalakan semua", "Uripake kabeh" },
                { "Matikan semua", "Patenana kabeh" },
                { "Keluar", "Metu" },
                { "(belum ada profil)", "(durung ana profil)" },
                { "berhenti", "mandheg" },
                { "jalan", "mlaku" },
                { "menyalakan", "nguripake" },
                { "mematikan", "matheni" },
                { "gagal", "gagal" },

                { "Pilih profil, lalu nyalakan. Ganti profil berarti ganti versi PHP, Apache, dan MySQL sekaligus.",
                  "Pilih profil, banjur uripake. Ganti profil tegese ganti versi PHP, Apache, lan MySQL sepisanan." },
                { "Profil aktif", "Profil sing aktif" },
                { "Switch & Jalankan", "Ganti & Uripake" },
                { "Switch", "Ganti" },
                { "Perhatian", "Gatekna" },
                { "Pintasan", "Dalan cepet" },
                { "Aktivitas", "Kagiyatan" },
                { "Buka www", "Bukak www" },
                { "Buka localhost", "Bukak localhost" },
                { "Beranda Phoron", "Ngarep Phoron" },
                { "Uji konfigurasi Apache", "Coba setelan Apache" },
                { "Buat sertifikat SSL", "Gawe sertifikat SSL" },
                { "Percayai sertifikat SSL", "Percaya sertifikat SSL" },
                { "Buat ulang sertifikat SSL", "Gawe maneh sertifikat SSL" },
                { "Folder etc", "Folder etc" },
                { "Unduh pembaruan", "Undhuh nganyari" },
                { "Jalankan ulang sebagai Administrator", "Mbaleni minangka Administrator" },
                { "Hentikan proses yang tertinggal", "Patenana proses sing keri" },
                { "belum dipilih di profil", "durung dipilih ing profil" },

                { "Satu profil = satu kombinasi versi + port. Simpan sebanyak yang perlu, lalu tinggal switch.",
                  "Siji profil = siji kombinasi versi lan port. Simpen samubarang sing perlu, banjur kari ganti." },
                { "Profil baru", "Profil anyar" },
                { "Duplikat", "Tiron" },
                { "Hapus", "Busak" },
                { "Nama profil", "Jeneng profil" },
                { "Versi PHP", "Versi PHP" },
                { "Versi Apache", "Versi Apache" },
                { "Versi MySQL / MariaDB", "Versi MySQL / MariaDB" },
                { "Folder proyek", "Folder proyek" },
                { "Tambah folder...", "Tambah folder..." },
                { "Akhiran nama situs", "Wuntat jeneng situs" },
                { "Catatan", "Cathetan" },
                { "Simpan", "Simpen" },
                { "Simpan lalu switch ke profil ini", "Simpen banjur ganti menyang profil iki" },

                { "Versi terpasang", "Versi sing kepasang" },
                { "Jenis", "Jinis" },
                { "Folder", "Folder" },
                { "Sumber", "Sumber" },
                { "Pindai ulang", "Sawang maneh" },
                { "Tambah folder bin", "Tambah folder bin" },
                { "Buka folder versi", "Bukak folder versi" },
                { "Pasang versi baru", "Pasang versi anyar" },
                { "Unduh & pasang", "Undhuh & pasang" },

                { "Buat situs", "Gawe situs" },
                { "Alamat", "Alamat" },
                { "Buka di browser", "Bukak ing browser" },
                { "Buka folder", "Bukak folder" },
                { "Terminal di sini", "Terminal ing kene" },
                { "Segarkan & sinkronkan", "Seger & selarasake" },
                { "Buka berkas hosts", "Bukak berkas hosts" },

                { "Jalankan Next.js, Astro, Vite, dan proyek Node lain dari folder mana pun.",
                  "Uripake Next.js, Astro, Vite, lan proyek Node liyane saka folder ngendi wae." },
                { "Proyek", "Proyek" },
                { "Perintah", "Printah" },
                { "Status", "Kahanan" },
                { "Skrip", "Skrip" },
                { "Jalankan", "Uripake" },
                { "Hentikan", "Patenana" },
                { "Tambah proyek...", "Tambah proyek..." },
                { "Buka alamat", "Bukak alamat" },
                { "Hapus dari daftar", "Busak saka dhaptar" },
                { "Keluaran", "Wetu" },

                { "Setelan php.ini yang sering diubah", "Setelan php.ini sing kerep diowahi" },
                { "Simpan ke profil", "Simpen menyang profil" },
                { "Ambil dari php.ini asli", "Jupuk saka php.ini asli" },
                { "Buka php.ini hasil", "Bukak php.ini asil" },

                { "Semua log Apache, MySQL, PHP, dan Phoron ada di folder logs.",
                  "Kabeh log Apache, MySQL, PHP, lan Phoron ana ing folder logs." },
                { "Muat ulang", "Muat maneh" },
                { "Kosongkan", "Kosongake" },
                { "Ikuti", "Tutake" },

                { "Setiap perubahan langsung tersimpan ke phoron.ini - tidak ada tombol simpan.",
                  "Saben owahan langsung kesimpen ing phoron.ini - ora ana tombol simpen." },
                { "Tampilan", "Tampilan" },
                { "Tema", "Tema" },
                { "Bahasa", "Basa" },
                { "Ikut Windows", "Melu Windows" },
                { "Terang", "Padhang" },
                { "Gelap", "Peteng" },
                { "Jalankan Phoron saat Windows dinyalakan", "Uripake Phoron nalika Windows urip" },
                { "Nyalakan layanan otomatis saat Phoron dibuka",
                  "Uripake layanan otomatis nalika Phoron dibukak" },
                { "Tombol tutup mengecilkan ke baki sistem, bukan keluar",
                  "Tombol tutup ngecilake menyang baki sistem, dudu metu" },
                { "Buat vhost otomatis untuk tiap folder di www",
                  "Gawe vhost otomatis kanggo saben folder ing www" },
                { "Sinkronkan berkas hosts Windows (butuh Administrator)",
                  "Selarasake berkas hosts Windows (butuh Administrator)" },
                { "Tampilkan beranda Phoron di http://localhost/",
                  "Tampilake ngarep Phoron ing http://localhost/" },
                { "Catat log rinci", "Cathet log rinci" },
                { "Tulis php.ini ke dalam folder PHP", "Tulis php.ini menyang folder PHP" },
                { "Folder bin yang dipindai", "Folder bin sing disawang" },
                { "Status hak akses", "Kahanan hak akses" },
                { "Folder Phoron", "Folder Phoron" },
                { "Buka folder instalasi", "Bukak folder instalasi" },
                { "Buka phoron.ini", "Bukak phoron.ini" },
                { "Buang blok hosts milik Phoron", "Buwang blok hosts duweke Phoron" },
                { "Pembaruan", "Nganyari" },
                { "Cek rilis baru di GitHub saat Phoron dibuka",
                  "Priksa rilis anyar ing GitHub nalika Phoron dibukak" },
                { "Cek pembaruan sekarang", "Priksa nganyari saiki" },
                { "Buka halaman rilis", "Bukak kaca rilis" },
            };
        }

        static Dictionary<string, string> Banjar_()
        {
            return new Dictionary<string, string>(StringComparer.Ordinal)
            {
                // Simpan-seketika di Profil dan Ekstensi
                { "Nyalakan ulang web server",
                  "Hidupakan pulang web server" },
                { "Switch ke profil ini",
                  "Ganti ka profil ngini" },
                { "Setiap centangan langsung tersimpan ke profil dan php.ini ditulis ulang - tidak ada tombol simpan.",
                  "Satiap centangan langsung tasimpan ka profil wan php.ini ditulis pulang - kadada tombol simpan." },
                { "Setiap perubahan langsung tersimpan ke berkas profil - tidak ada tombol simpan.",
                  "Satiap paubahan langsung tasimpan ka barakas profil - kadada tombol simpan." },
                // Halaman Tentang
                { "Tentang",
                  "Maklumat" },
                { "Yang sedang dipakai",
                  "Nang parhatan dipakai" },
                { "Tautan",
                  "Tautan" },
                { "Halaman proyek di GitHub",
                  "Laman proyek di GitHub" },
                { "Salin info versi",
                  "Salin maklumat versi" },
                { "pengguna biasa",
                  "pamakai biasa" },
                { "Info versi sudah disalin ke papan klip.",
                  "Maklumat versi sudah disalin ka papan ganda." },
                { "Lingkungan pengembangan web lokal: Apache, PHP, MySQL, dan Node dalam satu tempat, dengan kombinasi versi yang bisa disimpan sebagai profil lalu ditukar sekali klik.",
                  "Lingkungan pangembangan web lokal: Apache, PHP, MySQL, wan Node dalam sabuting wadah, lawan kombinasi versi nang kawa disimpan sabagai profil hanyar ditukar sakali klik." },
                { "Phoron memakai Apache, PHP, MySQL/MariaDB, Nginx, dan Node.js yang masing-masing punya lisensi sendiri. Phoron tidak pernah menulis ke dalam folder bin milik program itu - seluruh konfigurasi yang dihasilkan disimpan di folder etc.",
                  "Phoron mamakai Apache, PHP, MySQL/MariaDB, Nginx, wan Node.js nang masing-masingnya baisi lisensi surang. Phoron kada suah manulis ka dalam folder bin punya program itu - samunyaan konfigurasi nang diulah disimpan di folder etc." },
                // Daftar hosts sekali jalan
                { "Daftarkan nama situs sekali",
                  "Daptarakan ngaran situs sakali" },
                { "Saat dinyalakan Windows lewat autostart, Phoron selalu jalan tanpa hak Administrator - Windows memang begitu, supaya tidak ada kotak UAC di tiap boot. Entri berkas hosts sendiri menetap, jadi cukup didaftarkan sekali: sesudah itu nama .test tetap hidup walau Phoron jalan sebagai pengguna biasa.",
                  "Wayah dihidupakan Windows lewat autostart, Phoron salawasnya bajalan kada baisi hak Administrator - mamang aturan Windows, supaya kadada kutak UAC satiap boot. Entri barakas hosts tatap ada, jadi cukup didaptarakan sakali: imbah itu ngaran .test tatap hidup walau Phoron bajalan sabagai pamakai biasa." },
                { "Menyambung...",
                  "Manyambung..." },
                { "Batalkan",
                  "Pasahakan" },
                { "Apache berhenti",
                  "Apache pajah" },
                { "MySQL berhenti",
                  "MySQL pajah" },
                { "Centang ekstensi yang dipakai profil aktif.",
                  "Centangi ekstensi nang dipakai profil aktip." },
                { "Cari ekstensi...",
                  "Gagai ekstensi..." },
                { "Satu folder per baris; boleh lebih dari satu. Yang paling atas jadi akar utama (dilayani http://localhost). Kosongkan untuk memakai www bawaan.",
                  "Sabuting folder sabaris; kawa labih matan sabuting. Nang paling atas jadi akar utama (dilayani http://localhost). Kusungakan gasan mamakai www baku." },
                { "Phoron mulai langsung mengecil ke baki sistem, tanpa memunculkan jendela.",
                  "Phoron mulai langsung mangacil ka baki sistem, kada mamunculakan jandila." },
                { "Hanya alamat akar yang dialihkan. Subfolder seperti /simpdam/ tidak tersentuh, dan index.php milik folder proyek tetap bisa dibuka di /index.php. Matikan kalau akar folder proyek Anda memang aplikasi sendiri.",
                  "Hanya alamat akar nang dialihakan. Subfolder kaya /simpdam/ kada tasantuh, wan index.php punya folder proyek tatap kawa dibuka di /index.php. Pajahakan amun akar folder proyek Pian mamang aplikasi surang." },
                { "Baku mati agar Phoron ringan: log akses Apache dan seluruh keluaran layanan tidak ditulis (mysqld sendiri mencetak ratusan baris tiap kali menyala). Log GALAT Apache, MySQL, dan PHP tetap menyala — itulah yang menjelaskan kalau ada yang rusak.",
                  "Baku pajah supaya Phoron ringan: log akses Apache wan samunyaan kaluaran layanan kada ditulis (mysqld surang mancitak ratusan baris satiap kali hidup). Log KASALAHAN Apache, MySQL, wan PHP tatap hidup — itu nang manjalasakan amun ada nang rusak." },
                { @"Baku: php.ini ditulis ke etc\php\<versi>\ dan folder PHP tidak disentuh. Nyalakan kalau Anda ingin php.exe dari editor atau Composer di luar Phoron ikut memakai setelan yang sama. Hati-hati bila versi PHP-nya dipinjam dari Laragon - berkasnya dipakai bersama. php.ini asli dicadangkan sekali ke php.ini.sebelum-phoron.",
                  @"Baku: php.ini ditulis ka etc\php\<versi>\ wan folder PHP kada disantuh. Hidupakan amun Pian handak php.exe matan editor atawa Composer di luar Phoron umpat mamakai pangaturan nang sama. Hati-hati amun versi PHP-nya dipinjam matan Laragon - barakasnya dipakai basama. php.ini asli dicadangakan sakali ka php.ini.sebelum-phoron." },
                { "Satu folder per baris. Folder bin Laragon boleh ikut - Phoron tidak pernah menulis ke dalamnya.",
                  "Sabuting folder sabaris. Folder bin Laragon kawa umpat - Phoron kada suah manulis ka dalamnya." },
                { "Pengecekan dilewati kalau baru dilakukan dalam 6 jam terakhir - API GitHub tanpa token dibatasi 60 permintaan per jam.",
                  "Pamariksaan dilaluakan amun hanyar haja dilakuakan dalam 6 jam tarakhir - API GitHub kada pakai token dibatasi 60 pamintaan sajam." },
                { "Tiap subfolder di www otomatis dapat alamat sendiri.",
                  "Satiap subfolder di www otomatis dapat alamat surang." },
                { "Semua folder versi yang ditemukan di folder bin yang terdaftar. Folder bin Laragon ikut dipindai bila ada.",
                  "Samunyaan folder versi nang tatamu di folder bin nang tadaptar. Folder bin Laragon umpat digagai amun ada." },
                { @"Katalog unduhan (etc\catalog.ini)",
                  @"Katalog hunduhan (etc\catalog.ini)" },
                { "Katalog lokal",
                  "Katalog lokal" },
                { "Paket diunduh ke folder bin milik Phoron, tidak menyentuh folder Laragon.",
                  "Pakat dihunduh ka folder bin punya Phoron, kada manyantuh folder Laragon." },
                { "Beranda",
                  "Laman Muka" },
                { "Profil",
                  "Profil" },
                { "Versi",
                  "Versi" },
                { "Situs",
                  "Situs" },
                { "Ekstensi PHP",
                  "Ekstensi PHP" },
                { "Pengaturan",
                  "Pangaturan" },
                { "Nyalakan semua",
                  "Hidupakan samunyaan" },
                { "Matikan semua",
                  "Pajahakan samunyaan" },
                { "Keluar",
                  "Kaluar" },
                { "(belum ada profil)",
                  "(balum ada profil)" },
                { "berhenti",
                  "pajah" },
                { "jalan",
                  "bajalan" },
                { "menyalakan",
                  "mahidupakan" },
                { "mematikan",
                  "mamajahakan" },
                { "gagal",
                  "gagal" },
                { "Pilih profil, lalu nyalakan. Ganti profil berarti ganti versi PHP, Apache, dan MySQL sekaligus.",
                  "Pilih profil, hanyar hidupakan. Baganti profil artinya baganti versi PHP, Apache, wan MySQL sakalian." },
                { "Profil aktif",
                  "Profil nang aktip" },
                { "Switch & Jalankan",
                  "Ganti & Jalanakan" },
                { "Switch",
                  "Ganti" },
                { "Perhatian",
                  "Paringatan" },
                { "Pintasan",
                  "Jalan Singkat" },
                { "Aktivitas",
                  "Kagiatan" },
                { "Buka www",
                  "Buka www" },
                { "Buka localhost",
                  "Buka localhost" },
                { "Beranda Phoron",
                  "Laman Muka Phoron" },
                { "Uji konfigurasi Apache",
                  "Uji pangaturan Apache" },
                { "Buat sertifikat SSL",
                  "Ulah sertifikat SSL" },
                { "Percayai sertifikat SSL",
                  "Picayai sertifikat SSL" },
                { "Buat ulang sertifikat SSL",
                  "Ulah pulang sertifikat SSL" },
                { "Folder etc",
                  "Folder etc" },
                { "Unduh pembaruan",
                  "Hunduh pahanyaran" },
                { "Jalankan ulang sebagai Administrator",
                  "Jalanakan pulang sabagai Administrator" },
                { "Hentikan proses yang tertinggal",
                  "Pajahakan proses nang tatinggal" },
                { "belum dipilih di profil",
                  "balum dipilih di profil" },
                { "Satu profil = satu kombinasi versi + port. Simpan sebanyak yang perlu, lalu tinggal switch.",
                  "Sabuting profil = sabuting kombinasi versi wan port. Simpan sabanyak nang musti, hanyar tinggal ganti." },
                { "Profil baru",
                  "Profil hanyar" },
                { "Duplikat",
                  "Salinan" },
                { "Hapus",
                  "Hapus" },
                { "Nama profil",
                  "Ngaran profil" },
                { "Versi PHP",
                  "Versi PHP" },
                { "Versi Apache",
                  "Versi Apache" },
                { "Versi MySQL / MariaDB",
                  "Versi MySQL / MariaDB" },
                { "Folder proyek",
                  "Folder proyek" },
                { "Tambah folder...",
                  "Tambahi folder..." },
                { "Akhiran nama situs",
                  "Ujung ngaran situs" },
                { "Catatan",
                  "Catatan" },
                { "Simpan",
                  "Simpan" },
                { "Simpan lalu switch ke profil ini",
                  "Simpan hanyar ganti ka profil ngini" },
                { "Versi terpasang",
                  "Versi nang tapasang" },
                { "Jenis",
                  "Janis" },
                { "Folder",
                  "Folder" },
                { "Sumber",
                  "Sumber" },
                { "Pindai ulang",
                  "Gagai pulang" },
                { "Tambah folder bin",
                  "Tambahi folder bin" },
                { "Buka folder versi",
                  "Buka folder versi" },
                { "Pasang versi baru",
                  "Pasang versi hanyar" },
                { "Unduh & pasang",
                  "Hunduh & pasang" },
                { "Buat situs",
                  "Ulah situs" },
                { "Alamat",
                  "Alamat" },
                { "Buka di browser",
                  "Buka di browser" },
                { "Buka folder",
                  "Buka folder" },
                { "Terminal di sini",
                  "Terminal di sia" },
                { "Segarkan & sinkronkan",
                  "Hanyari & sinkronakan" },
                { "Buka berkas hosts",
                  "Buka barakas hosts" },
                { "Jalankan Next.js, Astro, Vite, dan proyek Node lain dari folder mana pun.",
                  "Jalanakan Next.js, Astro, Vite, wan proyek Node lainnya matan folder mana haja." },
                { "Proyek",
                  "Proyek" },
                { "Perintah",
                  "Parintah" },
                { "Status",
                  "Kaadaan" },
                { "Skrip",
                  "Skrip" },
                { "Jalankan",
                  "Jalanakan" },
                { "Hentikan",
                  "Pajahakan" },
                { "Tambah proyek...",
                  "Tambahi proyek..." },
                { "Buka alamat",
                  "Buka alamat" },
                { "Hapus dari daftar",
                  "Hapus matan daptar" },
                { "Keluaran",
                  "Kaluaran" },
                { "Setelan php.ini yang sering diubah",
                  "Pangaturan php.ini nang rancak diubah" },
                { "Simpan ke profil",
                  "Simpan ka profil" },
                { "Ambil dari php.ini asli",
                  "Ambil matan php.ini asli" },
                { "Buka php.ini hasil",
                  "Buka php.ini kulihan" },
                { "Semua log Apache, MySQL, PHP, dan Phoron ada di folder logs.",
                  "Samunyaan log Apache, MySQL, PHP, wan Phoron ada di folder logs." },
                { "Muat ulang",
                  "Muat pulang" },
                { "Kosongkan",
                  "Kusungakan" },
                { "Ikuti",
                  "Umpati" },
                { "Setiap perubahan langsung tersimpan ke phoron.ini - tidak ada tombol simpan.",
                  "Satiap paubahan langsung tasimpan ka phoron.ini - kadada tombol simpan." },
                { "Tampilan",
                  "Tampaian" },
                { "Tema",
                  "Tema" },
                { "Bahasa",
                  "Bahasa" },
                { "Ikut Windows",
                  "Umpat Windows" },
                { "Terang",
                  "Tarang" },
                { "Gelap",
                  "Kalam" },
                { "Jalankan Phoron saat Windows dinyalakan",
                  "Jalanakan Phoron wayah Windows dihidupakan" },
                { "Nyalakan layanan otomatis saat Phoron dibuka",
                  "Hidupakan layanan otomatis wayah Phoron dibuka" },
                { "Tombol tutup mengecilkan ke baki sistem, bukan keluar",
                  "Tombol tutup mangacilakan ka baki sistem, lain kaluar" },
                { "Buat vhost otomatis untuk tiap folder di www",
                  "Ulah vhost otomatis gasan satiap folder di www" },
                { "Sinkronkan berkas hosts Windows (butuh Administrator)",
                  "Sinkronakan barakas hosts Windows (musti Administrator)" },
                { "Tampilkan beranda Phoron di http://localhost/",
                  "Tampaiakan laman muka Phoron di http://localhost/" },
                { "Catat log rinci",
                  "Catat log rinci" },
                { "Tulis php.ini ke dalam folder PHP",
                  "Tulis php.ini ka dalam folder PHP" },
                { "Folder bin yang dipindai",
                  "Folder bin nang digagai" },
                { "Status hak akses",
                  "Kaadaan hak akses" },
                { "Folder Phoron",
                  "Folder Phoron" },
                { "Buka folder instalasi",
                  "Buka folder instalasi" },
                { "Buka phoron.ini",
                  "Buka phoron.ini" },
                { "Buang blok hosts milik Phoron",
                  "Buang blok hosts punya Phoron" },
                { "Pembaruan",
                  "Pahanyaran" },
                { "Cek rilis baru di GitHub saat Phoron dibuka",
                  "Pariksa rilis hanyar di GitHub wayah Phoron dibuka" },
                { "Cek pembaruan sekarang",
                  "Pariksa pahanyaran wayahini" },
                { "Buka halaman rilis",
                  "Buka laman rilis" },
            };
        }
    }
}
